# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches: ['**']
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.8'
            tox_env: py38-mitmproxy7,py38-mitmproxy8
          - python: '3.9'
            tox_env: py39-mitmproxy7,py39-mitmproxy8,py39-mitmproxy9
          - python: '3.10'
            tox_env: py310-mitmproxy7,py310-mitmproxy8,py310-mitmproxy9
          - python: '3.11'
            tox_env: py311-mitmproxy7,py311-mitmproxy8,py311-mitmproxy9
          - python: '3.12.0-beta.3 - 3.12'
            tox_env: py312-mitmproxy7,py312-mitmproxy8,py312-mitmproxy9
          - python: '3.11'
            tox_env: docs,doctests,linkcheck

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade tox
    - name: Run test suite
      run: |
        python -m tox run -e ${{ matrix.tox_env }}
